#!/bin/bash
# This script tags all modules listed in the "modules" file.
#
# Make sure to fix the set_urls function so that it uses the right tags.
# language_list becomes the subdirs file in the l10n module, make sure it's uptodate.
# Once it's all done, the script checks out the tagged directories under clean/.

BASE=svn+ssh://svn@svn.kde.org/home/kde

. versions

cd clean
for i in `cat ../modules`; do
  echo "$i..."
  set_urls $i
  if test -d $subname; then 
        svn switch $BASE/$HEADURL $subname
  else
        svn co $BASE/$HEADURL $subname
  fi
done

