#!/bin/bash
# Use this script to checkout the relevant parts of l10n
# Call it with the option "kde", "koffice", or "extragear-kmyapp"
# Currently only koffice is supported.

# This script generates the list of languages to be released,
# but after that you need to tag_all / removestuff anyway,
# so better package the tagged directory instead.

package=$1
CDPATH=

test -n "$package" || { echo "requires parameter"; exit 1; }
test -n "$SVNURL" || { echo "requires SVNURL to be set"; exit 1; }
test -d clean || { echo "create clean subdir"; exit 1; }
cd clean

if test "$package" = "koffice"; then
  ### Note that we're checking out stable
  L10N=$SVNURL/branches/stable/l10n
  svn co -N $L10N koffice-l10n
  cd koffice-l10n
  svn up scripts

  module=koffice
  # Checkout only the $module part of each language
  #cat ../../language_list | while read lang; do
  for lang in `svn ls $L10N`; do
    svn up -N $lang && test -d $lang && {
      svn up -N $lang/docs
      svn up -N $lang/messages
      svn up -N $lang/data
      svn up $lang/docs/$module
      svn up $lang/messages/$module
      svn up $lang/data/$module
    }
  done

  # Now select the languages with enough translations
  cp -f /dev/null ../../language_list.new
  total=0
  for i in en_GB/messages/koffice/*.po; do
    n=`msgfmt --statistics -o /dev/null $i 2>&1 | sed -e 's/,.*$//' | cut -d' ' -f1`
    total=$((total + $n))
  done
  required=$((total * 70 / 100))
  required=`echo $required | sed -e 's/\..*//'`
  echo "$total messages to translate, $required required as a minimum."
  for lang in *; do
    sum=0
    if test "$lang" != "templates" -a -d $lang/messages/koffice; then
      for i in $lang/messages/koffice/*.po; do
        n=`msgfmt --statistics -o /dev/null $i 2>&1 | sed -e 's/,.*$//' | cut -d' ' -f1`
        sum=$((sum + $n))
      done
      if test $sum -gt $required; then
        echo $lang: $sum/$total, keeping
        echo $lang >> ../../language_list.new
      else
        echo $lang: $sum/$total, dropping
        rm -rf $lang
      fi
    fi
  done
  echo "Languages selected, consider doing \"mv language_list.new language_list\" if OK"
fi

#if test "$package" = "kde"; then
  ## TODO: find or checkout a full kde-i18n
  ##       then remove the koffice and other non-released stuff
  ##       (i.e. call removestuff)
#fi
