#!/bin/bash -x

CDPATH=""

test -d build || { echo "build/ has to exist;"; exit 1; }
test -d install || { echo "install/ has to exist;"; exit 1; }

summary=$PWD/build/summary
log=$PWD/build/log
name=`basename $0`

date > $summary
date > $log
config=`cat config.options`
pwd=$PWD
for a in `cat modules`; do 
cd dirty
rm -rf $a-*
tar xf ../sources/$a-*.bz2
cd ..
rm -rf build/$a-*
mkdir build/$(basename dirty/$a-*)
  result=0
  if [ -e nobuild ]; then
     action="Skipping"
     result=1
  fi
  if [ $result$name == 0compile_all ]; then
     action="Configuring $PWD"
     echo $action
     cd build/$a-*
     cmake ../../dirty/$a-* $config >> $log 2>&1
     result=$?
     if [ $result == 0 ]; then
        cd ../.. 
     fi
  fi
  if [ $result == 0 ]; then
     action="Compiling $PWD"
     echo $action
     cd build/$a-*
     make -j30 >> $log 2>&1
     result=$?
  fi
  if [ $result == 0 ]; then
     action="Installing $PWD"
     echo $action
     cd build/$a-*
     make install >> $log 2>&1
     result=$?
  fi
  if [ $result == 0 ]; then
     action="Done"
     echo $action
  fi

  if [ "$action" == "Skipping" ]; then
     echo $PWD skipped.
     echo $PWD skipped. >> $summary
  elif [ "$action" == "Done" ]; then
     echo $PWD build ok. >> $summary
     touch nobuild
  else
     echo ERROR during $action
     echo ERROR during $action >> $summary
     if [ $a == kdelibs ]; then
        echo Aborted!
        echo Aborted! >> $summary
        exit 1;
     fi
  fi
  cd $pwd; 
done
