#!/bin/bash

. version

# E.g. 'October 06, 2014'
date=`date +'%B %d, %Y'`
# E.g. '06th October 2014'
otherdate="`date +'%d'`th `date +'%B %Y'`"

# If automatic date isn't what you want, set this instead
# Remember to comment it out afterwards
# date='October 07, 2014'
# otherdate='07th October 2014'

output=../www_info/source-kf-$version.inc
echo > $output

process_file()
{
    i=$1
    filename=`basename $i`
    echo '<tr valign="top">' >> $output
    l=`echo $filename | sed -e "s#.tar.xz##"`
    echo '   <td><a href="http://download.kde.org/stable/frameworks/'$version'/'$filename'">'$l'</a></td>' >> $output
    size=`stat -c "%s" $i`
    size=`echo "$size / 1024" | bc`
    if test "$size" -lt 1024; then
        size="$size"kB
    else
        size=`echo "($size * 10) / 1024" | bc`
        if test "$size" -lt 100; then
            size=`echo "$size"MB | sed -e "s#\(.\)MB#.\1MB#"`
        else
           size=`echo "$size"MB | sed -e "s#\(.\)MB#MB#"`
        fi
    fi
    echo '   <td align="right">'$size'</td>' >> $output
    sha1=`sha1sum $i | cut -f1 -d' '`
    echo '   <td><tt>'$sha1'</tt></td>' >> $output
    echo '</tr>' >> $output
    echo '' >> $output
}

process_folder()
{
    for i in $1/*.tar.xz; do 
        process_file $i
    done
}

onlyversion=$1

echo '<table border="0" cellpadding="4" cellspacing="0">' >> $output
echo '<tr valign="top">' >> $output
echo '  <th align="left">Location</th>' >> $output
echo '  <th align="left">Size</th>' >> $output
echo '  <th align="left">Sha1 Sum</th>' >> $output
echo '</tr>' >> $output

if [ -n "$onlyversion" ]; then
    for i in sources/*-$onlyversion.tar.xz; do
        process_file $i
    done
else
    process_folder "sources" "$onlyversion"
    if [ -d "sources/kde-l10n" ]; then
        process_folder "sources/kde-l10n"
    fi
fi

echo '</table>' >> $output

cd `dirname $output`
svn add `basename $output`

if [ -n "$onlyversion" ]; then
    exit 0
fi

##################
# Now create the main info page

cp kde-frameworks-template.php kde-frameworks-$version.php

perl -pi -e "s/5\.1\.0/$version/g" kde-frameworks-$version.php

svn add kde-frameworks-$version.php

#######
# Now create the announcement page

cd ../www_announcements
svn up

cp kde-frameworks-template.top kde-frameworks-$version.php

../release-tools/Markdown.pl ../release-tools/changelog | sed -e 's/"/\\"/g' >> kde-frameworks-$version.php

cat kde-frameworks-template.bottom >> kde-frameworks-$version.php

perl -pi -e "s/5\.1\.0/$version/g" kde-frameworks-$version.php
perl -pi -e "s/INSERT_DATE_HERE/$date/" kde-frameworks-$version.php

svn add kde-frameworks-$version.php

########
# Output lines for announcements/index.php

announcelines="<!-- KF $version -->
<strong>$otherdate</strong> - <a href=\\\"kde-frameworks-$version.php\\\">KDE Frameworks $version released</a>
<br />
\\\"<em>KDE Ships Frameworks $version.</em>\\\"
<p />"

perl -pi -e "\$_ .= \"$announcelines\" if (/INSERT NEW ENTRIES BELOW THIS LINE/);" index.php

#######
# Announcement email

echo "KDE Frameworks $version released"
echo
echo
echo "$otherdate. KDE today announces the release of KDE Frameworks $version."
echo
echo "KDE Frameworks are 60 addon libraries to Qt which provide a wide variety of "
echo "commonly needed functionality in mature, peer reviewed and well tested "
echo "libraries with friendly licensing terms. For an introduction see the "
echo "Frameworks 5.0 release announcement."
echo
sed -e 's/^#* //;s/^\*/ /' ../release-tools/changelog
echo
echo "http://kde.org/announcements/kde-frameworks-$version.php"

