#!/bin/sh 

sources=sources-oldrc5
test -z "$1" && { echo "parameter required"; exit 1; }
package=$1
test -r clean/$package || { echo "no clean/$package"; exit 1; }
test `ls -1 $sources/$package*bz2 | wc -l` = "1" || { echo "no tarball!"; exit 1; }
tarball="$sources/$package*bz2"
TOPLEVEL=`tar tjf $tarball | head -1 | sed -e 's,/$,,' `

rm -rf build/$package*
cd build
tar xjf ../$tarball 
diff -xMakefile.in -xCVS -aur $TOPLEVEL ../clean/$package > $package-diff
less $package-diff
