#! /bin/sh

umask 022
export VERBOSE=yes
export DOINGSNAPSHOT=yes

renice 20 $$

(cd ~/prod && cvs -l up)

# lets go work
cd ~/prod
rm -rf sources
mkdir sources
mkdir sources/kde-i18n

version=`date +%y%m%d`

for i in `cat snapmodules`; do 
(
  test -d clean/$i || { echo "$i doesn't exist"; exit 1; }

  ( cd clean/$i && cvs up )
  
  if test -n "`find clean/$i -type f \! -path \"*/CVS*\" -mtime -1`"; then 
      ./pack $i $version
      rm -f ftp/$i*bz2
      mv sources/$i*bz2 ftp
      if test "$i" = "kde-i18n"; then
          rm -f ftp/$i/$i*bz2
          mv sources/$i/$i*bz2 ftp/$i
      fi
  fi 

  ( cd dirty && rm -rf $i* )
)
done
