#!/bin/bash
# This is the main script.
# Call it with the package name as argument, like:  ./pack kdelibs
# Make sure to update the version numbers inside the script first.
#
# Environment variables taht can be set
# $scriptpath = path to kde-common/releases (by default: .. )

package=$1
version=$2

if test -z "$version"; then 

case $package in
  qt-copy)
    version=3.1_20021104
    ;;
  arts) 
    version=1.4.0
    ;;
  kdevelop)
    version=3.2.0
    ;;
  koffice)
    version=1.3.5
    ;;
  koffice-i18n)
    version=1.3.5
    ;;
  *)
    version=3.4.0
    ;;
esac

fi

if test -z "$scriptpath"; then
  scriptpath=".."
fi

CDPATH=""
unset UNSERMAKE # very important for now :)
export UNSERMAKE=no 

test -n "$package" || { echo "requires modulename as parameter"; exit 1; }
test -d clean || { echo "create clean subdir with cvs checkout"; exit 1; }
test -d dirty || mkdir dirty || { echo "create empty subdir dirty"; exit 1; }
test -d sources || mkdir sources || { echo "create empty subdir sources"; exit 1; }
test -d sources-old || { echo "create empty subdir sources-old with reference files for xdelta"; exit 1; }
if [ $package = kde-i18n ]; then
  test -d sources/kde-i18n || { echo "create empty subdir sources/kde-i18n"; exit 1; }
fi
if [ $package = koffice-i18n ]; then
  test -d sources/koffice-i18n || mkdir sources/koffice-i18n || { echo "create empty subdir sources/koffice-i18n"; exit 1; }
fi

test -d clean/$package || { echo "clean/$package does not exist"; exit 1; }
test -d dirty/$package-$version && { echo "rm -rf dirty/$package-$version"; rm -rf dirty/$package-$version; }
test -d dirty/$package && { echo "rm -rf dirty/$package"; rm -rf dirty/$package; }

if test -z "$HARDLINKS"; then
  echo "cp -pr clean/$package dirty"
  cp -pr clean/$package dirty || exit 1
else
  echo "cp -prl clean/$package dirty"
  cp -prl clean/$package dirty || exit 1
fi
{
  echo "cd dirty"
  cd dirty || exit 1

if test -z "$DOINGSNAPSHOT"; then
  if [ "$package" = "kde-i18n" ]; then
    mv $package/subdirs $package/subdirs.orig
    cp ../language_list $package/subdirs
  fi

  # remove nonreleased stuff
  echo "removestuff $package"
  $scriptpath/removestuff $package $version || exit 1
fi

  # Anonymize the CVS dirs
  echo "anon $package"
  $scriptpath/anon $package || exit 1
 
if test -z "$DOINGSNAPSHOT"; then
  # Generate docu
  echo "docu $package"
  $scriptpath/docu $package 
fi

  # Prepare for distribution
  echo "dist $package"
  $scriptpath/dist $package $version || exit 1

  # Final packaging
  echo "mv $package $package-$version"
  mv $package $package-$version || exit 1
  echo "tar cjf $package-$version.tar.bz2 $package-$version"
  tar --owner=root --group=root -cf $package-$version.tar $package-$version || exit 1

  if test "$package" = "kde-i18n"; then
    cd ../sources
    # for kde-i18n we only generate xdelta for the small files
    files=`cd ../sources/kde-i18n && ls -1 kde-i18n-*-$version.tar.bz2 2> /dev/null`
    for file in $files; do
	lang=${file/kde-i18n-/}
	lang=${lang/-$version.tar.bz2/}
	oldlang=`ls -1 ../sources-old/kde-i18n/kde-i18n-$lang-*tar.bz2 2>/dev/null | tail -n 1`
	if test -n "$oldlang" && test -r "$oldlang"; then
	    cp $oldlang kde-i18n
	    echo "bunzip2 kde-i18n/kde-i18n-$lang-$version.tar.bz2"
	    bunzip2 kde-i18n/kde-i18n-$lang-$version.tar.bz2
            cd kde-i18n 
            ../$scriptpath/xdelta kde-i18n-$lang-*.bz2 kde-i18n-$lang-$version.tar
	    cd ..
	    rm -f kde-i18n/kde-i18n-$lang-*.bz2
            echo "bzip2 kde-i18n/kde-i18n-$lang-$version.tar"
	    bzip2 kde-i18n/kde-i18n-$lang-$version.tar
        fi
    done
    cd ../dirty

  else
    # generate xdeltas
    if test "$package" = "koffice"; then
        # For KOffice, the modules are named "koffice" and "koffice-i18n"
        # so search for koffice*tar.bz2 returns 2 files.
        oldpackage=`ls -1 ../sources-old/$package*tar.bz2 2>/dev/null | fgrep -v i18n`
    else
        # Normal case, no problem with a pseudo-duplicate
        oldpackage=`ls -1 ../sources-old/$package*tar.bz2 2>/dev/null | tail -n 1`
    fi
    if test -n "$oldpackage" && test -r $oldpackage; then 
        cp $oldpackage .
        $scriptpath/xdelta $package*tar.bz2 $package*tar
        mv $package*.tar.xdelta ../sources
    fi
  fi

  bzip2 -9 $package-$version.tar
  mv $package-$version.tar.bz2 ../sources
  rm -f $package*tar
  rm -rf $package-$version
}
rm -rf dirty/$package || exit 1
