#!/bin/bash
# vim: sw=2 et

# This is a helper script, which removes the useless stuff from some modules.
# Call it with the package name as argument, like:  ./removestuff kde-l10n

# This is called by tag_all with DO_SVN=1 in order to remove unused stuff from a tag.

source `dirname $0`/common $1 $2

# If last element in a path contains @-character, svn may interpret it as
# a revision number separator, depending on command and argument position.
# This can be escaped by adding one trailing @ to such paths.
# svn rm: all path arguments sensitive to @
svn_rm () {
    paths_esc=
    for rawpath in "$@"; do paths_esc="$paths_esc '$rawpath@'"; done
    eval "svn rm $paths_esc"
}

rm_command="rm -rf"
if test -n "$DO_SVN"; then
  rm_command=svn_rm
#  rm_command="rm -rf"
fi

cd_package()
{
  if test -n "$version" && test -d $package-$version; then
    cd $package-$version
  else
    cd $package || { echo "bah! $package doesn't exist in $PWD"; exit 1; }
  fi
}

  if [ $package = "kde-l10n" ]; then
  (
     cd_package
     echo "Removing other stuff"
     cat */pack-with-variants subdirs | sort -u | while read lang; do
       cd $lang || continue
       $rm_command internal 
       $rm_command docmessages 
       $rm_command webmessages 
       $rm_command messages/*/desktop_* 
       $rm_command messages/others 
       $rm_command messages/index.lokalize
       $rm_command docs/others 
       $rm_command messages/kdenonbeta 
       $rm_command docs/kdenonbeta 
       $rm_command messages/extragear-*
       $rm_command messages/www
       $rm_command messages/playground-*
       $rm_command messages/no-auto-merge
       $rm_command docs/extragear-* 
       $rm_command docs/playground-*
       $rm_command messages/kdekiosk
       $rm_command docs/kdekiosk 
       $rm_command messages/play* 
       $rm_command messages/kdereview 
       $rm_command */koffice 
       $rm_command */calligra
       $rm_command messages/kdevelop
       $rm_command docs/kdevelop
       $rm_command messages/kdevplatform
       $rm_command docs/kdevplatform
       $rm_command docs/kdewebdev/quanta*
       $rm_command messages/kdewebdev/quanta*
       $rm_command no-auto-merge
       $rm_command */no-auto-merge

#       $rm_command messages/kdenetwork/kopete*
#       $rm_command docs/kdenetwork/kopete*
#       test -d docs/common || {
#            echo "$lang/docs/common not translated, removing" 
#            $rm_command docs 
#       }
       cd ..
     done
     echo "Removing template specific stuff"
     $rm_command templates
  )
  fi

  if [ $package = "kde-l10n" ]; then
  (
    cd_package

    if test -z "$DO_SVN"; then
      echo "Moving language variants to be packed together"
      for dir in *; do
        if test -f $dir/pack-with-variants; then
          cat $dir/pack-with-variants | while read vdir; do
            echo Moving $vdir into $dir
            mv $vdir $dir
          done
          $rm_command $dir/pack-with-variants
        fi
      done
    fi

    echo Removing non-released languages from package
    grep ^xx subdirs && { echo "$package/subdirs contains the xx language!"; exit 1; }
    for dir in *; do
	if test -d $dir/messages -o -d $dir/docs; then
            if grep -q ^$dir\$ subdirs; then
                 echo Keeping $dir
            else
                 echo Deleting $dir
                 $rm_command $dir
	    fi
        fi

        # some languages directories may be entirely empty
        # by this point.
        if test -d $dir ; then
          files=`ls -1 $dir | wc -l`
          test $files -eq 0 && $rm_command $dir
        fi

    done
    ) || exit 1
  fi

  # generic stuff
  (
     cd_package
     rm -f svn-commit*.*
  )

