#!/bin/bash
version=4.9.3

SVNUSER=tnyblom
SVNPROTOCOL=svn+ssh

test -n "$SVNUSER" || { echo "You must set SVNUSER"; exit 1; }
test -n "$SVNPROTOCOL" || { echo "You must set SVNPROTOCOL"; exit 1; }

TAGDIR=$SVNPROTOCOL://$SVNUSER@svn.kde.org/home/kde/tags/KDE/${version}

svn mkdir $TAGDIR

rm FAILED_TAGGED_LOG

for d in clean/*; do
    pushd $d 2> /dev/null > /dev/null
    if [ -d .git ]; then
        echo "=> Tagging git repo $d"
        echo git tag -a -m "KDE/$version" v$version && git push --tags || echo $d >> FAILED_TAGGING_LOG
    elif [ -d .svn ]; then
        echo "=> Tagging svn repo $d"
        rev=$(svn info | sed -n -e '/^Revision: \([0-9]*\).*$/s//\1/p')
        branchurl=$(svn info | sed -n -e '/^URL: \(.*\)$/s//\1/p')
        tagurl=`basename ${branchurl}`

        svn copy -m"$version" $branchurl@$rev $TAGDIR/$tagurl || echo $tagurl >> FAILED_TAGGING_LOG
    fi
    popd 2> /dev/null > /dev/null
done
