#!/bin/bash
# vim: sw=2

source `dirname $0`/common $1 $2

compressors="pbzip2 bzip2"
#compressors="pixz xz $compressors"

for c in $compressors; do
  compress=$(type -p $c)
  if [ x"$compress" != "x" ]; then
    if [ -x $compress ]; then
      break;
    fi
  fi
done

if ! [ -x $compress ] ; then
  echo "error: need one of $compressors installed."
  exit 1
fi

if test $isl10n -eq 1; then
  cd $package
  echo "making per-language tarballs"
  cat subdirs | while read lang; do
    rsubdir=$package-$lang-$version
    mv $lang $rsubdir
    tar --owner=root --group=root -c --exclude autom4te.cache $rsubdir | $compress -9 > ../../sources/$package/$rsubdir.tar.bz2
    mv $rsubdir $lang
  done
  cd ..
else
 echo "mv $package $package-$version"
 mv $package $package-$version || exit 1
 echo "tar --owner=root --group=root -c -I $compress -f $package-$version.tar.bz2 $package-$version"
 tar --owner=root --group=root -c -I $compress -f $package-$version.tar.bz2 $package-$version || exit 1
fi

if test $isl10n -eq 0; then
  mv $package-$version.tar.bz2 ../sources
  echo "rm -f $package*tar"
  rm -f $package*tar
  echo "rm -rf $package-$version"
  rm -rf $package-$version
fi

rm -rf dirty/$package || exit 1
