######################################################################
# Automatically generated by qmake (2.01a) vr mei 21 22:28:30 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . backup
INCLUDEPATH += .

# Input
HEADERS += mainclass.h
FORMS += mainclass.ui
SOURCES += main.cpp mainclass.cpp
